### ISSUE TITLE
Create responsive YouTube embed capability

### ISSUE THREAD

**Issue by digitalman2112** [makerfx/makerfx.org#12]
How to: https://avexdesigns.com/blog/responsive-youtube-embed

Might be a good use case for a jekyll include where you just pass the youtube video url...

https://jekyllrb.com/docs/includes/

**Comment by 107pilot** [comment]
Is there a particular page/video we should install youtube embed videos, or maybe thinking we make a new page?

**Comment by digitalman2112** [comment]
Ideally, this would be an include that we could add to any page.

As an example, the /magic-wheelchair page has some embeds, but they are not
responsive.

**Comment by digitalman2112** [comment]
Jeff fixed this in #16, closing
