### ISSUE TITLE
Site not loading properly on mobile

### ISSUE THREAD

**Issue by digitalman2112** [makerfx/makerfx.org#18]
Screenshot

![Screenshot_20210608-071549.png](https://user-images.githubusercontent.com/452840/121175842-87a6c500-c829-11eb-8d0f-7c5c29b7143f.png)

Iirc, there is a header that needs to be added, had same issue on MFO site.

**Comment by digitalman2112** [comment]
I think this is the line 

`<meta name="viewport" content="width=device-width, initial-scale=1">`

need to add to <head> and test

**Comment by jeffdriscoll** [comment]
What is the issue?  I am not seeing it in the screenshot.

**Comment by jeffdriscoll** [comment]
Ok. Change made and Membership, Virtual Tour and Donate pages render better on a mobile device.  The Home page is different.  Researching.

**Comment by jeffdriscoll** [comment]
It is working now. I had to refresh to drop the cached version on the phone.

**Comment by digitalman2112** [comment]
thanks @jeffdriscoll
